In [2]:
import numpy as np

In [3]:
#we can use all of the data structures into array [#one diamension]
array=np.array([1,1.5,True,'string'])

In [4]:
array


array(['1', '1.5', 'True', 'string'], dtype='<U32')

In [5]:
#creating zeros function
zeros=np.zeros(6)

In [6]:
zeros

array([0., 0., 0., 0., 0., 0.])

In [7]:
#creating ones function
ones=np.ones(6)

In [8]:
ones

array([1., 1., 1., 1., 1., 1.])

In [9]:
#creating range function
range = np.arange(12)

In [11]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
#creating linspace function to evenly splited
linspace=np.linspace(1,35,3)

In [23]:
linspace

array([ 1., 18., 35.])

In [24]:
len(range)

12

In [43]:
#creating 2d array[2 diamension]

In [36]:
inn=np.array([[1,2,3],[6,8,0],[1,2,3]])

In [40]:
#type cheacking
type(inn)

numpy.ndarray

In [39]:
#find a shape of array
inn.shape

(3, 3)

In [37]:
#find the size of array
inn.size

9

In [38]:
#find the length
len(inn)

3

In [41]:
#dimension
inn.ndim

2

In [42]:
#conveting one diamension to two diamension[1d to 2d]

In [44]:
#reshape and resize function

In [46]:
inr=np.arange(12)

In [47]:
#one diamension
inr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
inr.shape


(12,)

In [51]:
inr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
inr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [57]:
inr.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [54]:
#resize of array to 2d

In [58]:
inr.resize(4,3)

In [59]:
inr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [63]:
imr=np.hsplit(inr,3)

In [64]:
imr

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [65]:
vijay,ajith,kumar=np.hsplit(inr,3)


In [66]:
vijay

array([[0],
       [3],
       [6],
       [9]])

In [67]:
ajith

array([[ 1],
       [ 4],
       [ 7],
       [10]])

In [86]:
#creating 3d array 

In [82]:
war = np.array([[   [[1,2,3],[4,7,9],[7,6,3]],[[1,2,3],[4,7,9],[7,6,3]]    ]])


In [87]:
war.ndim

3

In [89]:
war.shape

(1, 6, 3)

In [90]:
war


array([[[1, 2, 3],
        [4, 7, 9],
        [7, 6, 3],
        [1, 2, 3],
        [4, 7, 9],
        [7, 6, 3]]])

In [100]:
war1=np.array([[[1,2,3],[2,4,5]],[[4,7,9],[2,7,9]]])

In [101]:
war1.ndim

3

In [104]:
war1.shape

(2, 2, 3)

In [103]:
war1

array([[[1, 2, 3],
        [2, 4, 5]],

       [[4, 7, 9],
        [2, 7, 9]]])

In [108]:
#accessing element
war1[0][0][2]

3

In [110]:
war1[0,1,2]

5