In [1]:
#importing library
import numpy as np

In [6]:
oneD=np.array([1,2,3,4,5,6,7,8])
twoD=np.array([[1,2,3],[3,2,1]])
threeD=np.array([[[1,2,3],[3,2,1],[6,7,8]]])

In [ ]:
#finding the diamesion

In [3]:
oneD.ndim

1

In [4]:
twoD.ndim

2

In [7]:
threeD.ndim

3

In [8]:
#slicing

In [9]:
oneD[0]

1

In [10]:
oneD[4]

5

In [11]:
oneD[2]

3

In [ ]:
#two diamwnsional slicing

In [12]:
twoD

array([[1, 2, 3],
       [3, 2, 1]])

In [15]:
#Axis
"""twoD(row ,column )"""

'twoD(row ,column )'

In [16]:
twoD[0,0]

1

In [17]:
twoD[1,0]

3

In [18]:
twoD[0,2]

3

In [19]:
twoD[1,1]

2

In [21]:
twoD[1,2]

1

In [30]:
twoD[1,1:]

array([2, 1])

In [31]:
#three diamensional
threeD

array([[[1, 2, 3],
        [3, 2, 1],
        [6, 7, 8]]])

In [32]:
threeD[1,1,0]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [ ]:
threeD[0,0,0]