In [45]:

#first we want to import numpy and giving alise name as np
import numpy as np

#create a new ndarray (one dimensional) using arange fucntion
array=np.arange(12)
oneD_array=np.array([array])
#print oneD_array
print(array)

#creating two Diamensional array
twoD_array=np.reshape(oneD_array,(6,2))
print(twoD_array)

#craete a three  Diamensional array using range function
threeD=np.arange(27)

threeD_array=np.reshape(threeD,(3,3,3))

print("#Three Diamnesion" )
print(threeD_array)

#finding the shape of ndarray
np.shape(threeD_array)

#finding the diamension of ndarray
np.ndim(threeD_array)

#idexing and slicing

data = np.array([1, 2, 3])

data[1]


data[0:2]


data[1:]


data[-2:]




array([2, 3])

In [52]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a[a<5])
print(a[a>=5])

[1 2 3 4]
[ 5  6  7  8  9 10 11 12]
