In [1]:
import numpy as np

In [23]:
arr=np.array([[3,9,4],[7,5,3],[8,0,21]])

In [29]:
arr

array([[ 3,  9,  4],
       [ 7,  5,  3],
       [ 8,  0, 21]])

In [27]:
#finding minimum value
#axis = 0 and axis = 1

In [24]:
np.amin(arr,axis=0)

array([3, 0, 3])

In [25]:
np.amin(arr,axis=1)

array([3, 3, 0])

In [26]:
np.max(arr)

21

In [28]:
np.max(arr,axis=0)

array([ 8,  9, 21])

In [30]:
np.max(arr,axis=1)

array([ 9,  7, 21])

In [31]:
np.median(arr)

5.0

In [32]:
np.mean(arr)

6.666666666666667

In [33]:
np.std(arr)

5.715476066494082

In [34]:
np.var(arr)

32.666666666666664

In [36]:
np.percentile(arr,3)

0.72

In [37]:
# find the sin , cos ,tan values

In [40]:
deg = np.array([0,30,45,60,90,180])
deg

array([  0,  30,  45,  60,  90, 180])

In [39]:
np.sin(deg*np.pi/180)

array([0.00000000e+00, 5.00000000e-01, 7.07106781e-01, 8.66025404e-01,
       1.00000000e+00, 1.22464680e-16])

In [41]:
np.cos(deg*np.pi/180)

array([ 1.00000000e+00,  8.66025404e-01,  7.07106781e-01,  5.00000000e-01,
        6.12323400e-17, -1.00000000e+00])

In [42]:
np.tan(deg*np.pi/180)

array([ 0.00000000e+00,  5.77350269e-01,  1.00000000e+00,  1.73205081e+00,
        1.63312394e+16, -1.22464680e-16])

In [47]:
arr=np.array([12.5,20.9,30,-32,-45,-56])

In [48]:
np.floor(arr)

array([ 12.,  20.,  30., -32., -45., -56.])